# Site settings
author: Elsa Xue Chen
title: TECH STYLE
header-img: img/home-bg.png
email: snowing222@gmail.com
copyright_name: Elsa Xue Chen
description: > # this means to ignore newlines until "baseurl:"
  I KNOW...BUT WHY?
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Snowing222

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
